name: Bump code and build version number
on:
  push:
    branches:
      - main
      - 2.0.x

jobs:
  bump-code:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_COMMIT }}

      - name: version code
        id: version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
      - name: version build
        id: version_build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'

      - name: new version code
        id: new_version_code
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_code.outputs.value }} + 1" | bc)"
      - name: new version build
        id: new_version_build
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_build.outputs.value }} + 1" | bc)"

      - name: Update version code
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
          value: ${{ steps.new_version_code.outputs.value }}
      - name: Update version build
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'
          value: ${{ steps.new_version_build.outputs.value }}

      - name: Push new files back to branch.
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Code and Build version bump, #skip-ci"
          status_options: '--untracked-files=no'
          disable_globbing: true
