name: Build main release
on:
  push:
    branches:
      - main

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          wrapper-cache-enabled: false
          dependencies-cache-enabled: false
          configuration-cache-enabled: false
          arguments: build assembleDebug bundleDebug assembleRelease bundleRelease


      #- name: Run Unit Tests with emulator
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    target: default
      #    arch: x86
      #    profile: Nexus 6
      #    script: ./gradlew connectedCheck --stacktrace
      ## Sign our artifact##
      - name: Sign apk artifact
        id: signArtifactApk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign bundle artifact
        id: signArtifactBundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: apk_name
        id: apk_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/release/output-metadata.json)"

      - name: bundle_name
        id: bundle_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/release/output-metadata.json|sed 's/.apk/.aab/')"

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.apk_name.outputs.file_name}}
          path: ${{steps.signArtifactApk.outputs.signedReleaseFile}}

      - name: Upload our Bundle
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.bundle_name.outputs.file_name}}
          path: ${{steps.signArtifactBundle.outputs.signedReleaseFile}}

      - name: Push new files back to branch.
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "Patch version bump, #skip-ci"
          status_options: '--untracked-files=no'
          disable_globbing: true
