name: Build debug
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!2.0.x'

jobs:
  build-debug:
    if: "!contains(github.event.head_commit.message, '#skip-ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}
      - name: version patch
        id: version_patch
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_PATCH'
      - name: version code
        id: version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
      - name: version build
        id: version_build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'

      - name: new version patch
        id: new_version_patch
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_patch.outputs.value }} + 1" | bc)"
      - name: new version code
        id: new_version_code
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_code.outputs.value }} + 1" | bc)"
      - name: new version build
        id: new_version_build
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_build.outputs.value }} + 1" | bc)"

      # Not need to update version patch, it will be updated when doing release.
      - name: Update version code
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
          value: ${{ steps.new_version_code.outputs.value }}
      - name: Update version build
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'
          value: ${{ steps.new_version_build.outputs.value }}

      - name: Access PLACES_API_KEY
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'local.properties'
          property: 'places_api_key'
          value: \"${{ secrets.API_KEY }}\"

      - name: Build all artifacts
        id: buildAllApks
        run: ./gradlew build assembleDebug bundleDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload our Bundle
        uses: actions/upload-artifact@master
        with:
          path: app/build/outputs/bundle/debug/*.aab

      - name: Upload lint report
        uses: actions/upload-artifact@master
        with:
          name: 'lint-results.html'
          path: app/build/reports/lint-results.html
