name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
          dependencies-cache-key: |
            **/gradle.properties
            gradle/dependency-locks/**
          dependencies-cache-exact: true
          configuration-cache-key: |
            **/gradle.properties
            gradle/dependency-locks/**
          configuration-cache-exact: true
      #- name: Run Unit Tests with emulator
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    target: default
      #    arch: x86
      #    profile: Nexus 6
      #    script: ./gradlew connectedCheck --stacktrace
      ## Sign our artifact##
      - name: Sign apk artifact
        id: signArtifactApk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      -name: test
        id: test
        run: echo ${{steps.signArtifactApk.outputs.signedReleaseFile}}

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          name: com.digitalruiz.com.pizzadriver-release.apk
          path: ${{steps.signArtifactApk.outputs.signedReleaseFile}}



