name: Build debug
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}
      - name: version code
        id: version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          prop_path: 'VERSION_CODE_NUMBER'
      - name: version build
        id: version_build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          prop_path: 'VERSION_BUILD'
      - name: Update version code
        uses: christian-draeger/write-properties@1.0.1
        with:
          file: 'app/version.properties'
          field: 'VERSION_CODE_NUMBER'
          value: ${{ steps.version_code.outputs.value }} + 1
      - name: Update version build
        uses: jossef/action-set-json-field@v1
        with:
          file: 'app/version.properties'
          field: 'VERSION_BUILD'
          value: ${{ steps.version_build.outputs.value }} + 1
      - name: Build all artifacts
        id: buildAllApks
        run: ./gradlew assembleDebug bundleDebug --stacktrace --info



      #- name: Run Unit Tests with emulator
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    target: default
      #    arch: x86
      #    profile: Nexus 6
      #    script: ./gradlew connectedCheck --stacktrace

      - name: apk_name
        id: apk_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/debug/output-metadata.json)"

      - name: bundle_name
        id: bundle_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/debug/output-metadata.json|sed 's/.apk/.aab/')"

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.apk_name.outputs.file_name}}
          path: app/build/outputs/apk/debug/${{steps.apk_name.outputs.file_name}}

      - name: Upload our Bundle
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.bundle_name.outputs.file_name}}
          path: app/build/outputs/bundle/debug/app-debug.aab

      - name: Push new files back to branch.
        if: "!contains(github.event.head_commit.message, 'skip-ci')"
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "Build version bump, #skip-ci"
          status_options: '--untracked-files=no'
          disable_globbing: true



