name: Build branch release
on:
  push:
    branches:
      - 1.5.x
      - 2.0.x

jobs:
  build-branch:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}
      - name: version patch
        id: version_patch
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_PATCH'
      - name: version code
        id: version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
      - name: version build
        id: version_build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'

      - name: new version patch
        id: new_version_patch
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_patch.outputs.value }} + 1" | bc)"
      - name: new version code
        id: new_version_code
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_code.outputs.value }} + 1" | bc)"
      - name: new version build
        id: new_version_build
        run: echo "##[set-output name=value;]$(echo "${{ steps.version_build.outputs.value }} + 1" | bc)"

      # Not need to update version patch, will be taken care in release
      - name: Update version code
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_CODE_NUMBER'
          value: ${{ steps.new_version_code.outputs.value }}
      - name: Update version build
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_BUILD'
          value: ${{ steps.new_version_build.outputs.value }}

      - name: Build all artifacts
        id: buildAllApks
        run: ./gradlew build assembleRelease bundleRelease

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


      - name: Sign apk artifact
        id: signArtifactApk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign bundle artifact
        id: signArtifactBundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: apk_name
        id: apk_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/release/output-metadata.json)"

      - name: bundle_name
        id: bundle_name
        run: echo "##[set-output name=file_name;]$(jq -r '.elements[].outputFile' app/build/outputs/apk/release/output-metadata.json|sed 's/.apk/.aab/')"

      - name: Upload our APK
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.apk_name.outputs.file_name}}
          path: ${{steps.signArtifactApk.outputs.signedReleaseFile}}

      - name: Upload our Bundle
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.bundle_name.outputs.file_name}}
          path: ${{steps.signArtifactBundle.outputs.signedReleaseFile}}

      - name: Upload lint report
        uses: actions/upload-artifact@master
        with:
          name: 'lint-results.html'
          path: app/build/reports/lint-results.html

      - name: Push new files back to branch.
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "Code and Build version bump, #skip-ci"
          status_options: '--untracked-files=no'
          disable_globbing: true
